# Generated by Django 5.1.2 on 2024-10-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_user_location_user_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='loc_id',
        ),
    ]
