# Generated by Django 5.1.2 on 2024-11-15 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads_management', '0001_initial'),
        ('location_management', '0001_initial'),
        ('venue_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_number', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.DateField()),
                ('slot', models.CharField(choices=[('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=10)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='leads_management.lead')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location_management.location')),
                ('occasion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking_link', to='leads_management.occasion')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venue_management.venue')),
            ],
            options={
                'ordering': ['-booking_date'],
                'unique_together': {('venue', 'slot', 'event_date')},
            },
        ),
    ]
