# Generated by Django 5.1.2 on 2024-11-04 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings_management', '0001_initial'),
        ('leads_management', '0001_initial'),
        ('location_management', '0003_alter_location_loc_id'),
        ('venue_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='leads_management.lead'),
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location_management.location'),
        ),
        migrations.AddField(
            model_name='booking',
            name='sales_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venue_management.venue'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('venue', 'event_date', 'slot')},
        ),
    ]
