# Generated by Django 5.1.2 on 2024-11-15 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings_management', '0001_initial'),
        ('leads_management', '0001_initial'),
        ('location_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='leads_management.lead'),
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location_management.location'),
        ),
    ]
