# Generated by Django 5.1.2 on 2024-11-15 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_management', '0001_initial'),
        ('leads_management', '0001_initial'),
        ('venue_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('venue', 'event_date', 'slot')},
        ),
        migrations.AlterField(
            model_name='booking',
            name='occasion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='leads_management.occasion'),
        ),
    ]
