# Generated by Django 5.1.2 on 2025-01-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='loc_id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=510),
        ),
    ]
