# Generated by Django 5.1.2 on 2024-10-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_admin',
        ),
    ]
