# Generated by Django 5.1.2 on 2024-10-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='location',
            new_name='location_id',
        ),
    ]
