# Generated by Django 5.1.2 on 2024-11-12 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_management', '0002_initial'),
        ('leads_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='haldi',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='haldi',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='mehndi',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='mehndi',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='roka',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='roka',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='sagan',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='sagan',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='remark',
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion_type', models.CharField(choices=[('engagement', 'Engagement'), ('wedding', 'Wedding'), ('reception', 'Reception'), ('sagan', 'Sagan'), ('roka', 'Roka'), ('haldi', 'Haldi'), ('mehndi', 'Mehndi'), ('corporate', 'Corporate'), ('room', 'Room')], max_length=20)),
                ('date_of_function', models.DateField(blank=True, null=True)),
                ('day', models.CharField(blank=True, max_length=10)),
                ('lunch_pax', models.IntegerField(default=0)),
                ('hi_tea_pax', models.IntegerField(default=0)),
                ('dinner_pax', models.IntegerField(default=0)),
                ('dj_value', models.IntegerField(default=0)),
                ('decor_value', models.IntegerField(default=0)),
                ('liquor_value', models.IntegerField(default=0)),
                ('vedi_value', models.IntegerField(default=0)),
                ('number_of_pax', models.IntegerField(default=0)),
                ('number_of_rooms', models.IntegerField(default=0)),
                ('plan', models.CharField(blank=True, max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occasions', to='bookings_management.booking')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occasions', to='leads_management.lead')),
            ],
            options={
                'ordering': ['date_of_function'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_pax', models.IntegerField()),
                ('number_of_rooms', models.IntegerField()),
                ('plan', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='bookings_management.booking')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='leads_management.lead')),
            ],
        ),
        migrations.DeleteModel(
            name='Corporate',
        ),
        migrations.DeleteModel(
            name='Engagement',
        ),
        migrations.DeleteModel(
            name='Haldi',
        ),
        migrations.DeleteModel(
            name='Mehndi',
        ),
        migrations.DeleteModel(
            name='Reception',
        ),
        migrations.DeleteModel(
            name='Roka',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
        migrations.DeleteModel(
            name='Sagan',
        ),
        migrations.DeleteModel(
            name='Wedding',
        ),
    ]
