# Generated by Django 5.1.2 on 2024-10-20 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_management', '0001_initial'),
        ('location_management', '0003_alter_location_loc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_management.location'),
        ),
    ]
