# Generated by Django 5.1.2 on 2025-02-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
