# Generated by Django 5.1.2 on 2024-11-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads_management', '0002_remove_engagement_booking_remove_engagement_lead_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
