# Generated by Django 5.1.2 on 2024-10-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads_management', '0002_rename_location_lead_location_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='venue',
            new_name='venue_id',
        ),
    ]
