# Generated by Django 5.1.2 on 2025-02-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_management', '0003_add_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(choices=[('walk_in', 'Walk In'), ('social_media', 'Social Media'), ('google', 'Google'), ('referral', 'Referral'), ('wedding_wire', 'Wedding Wire'), ('wed_me_good', 'Wed Me Good'), ('venue_look', 'Venue Look'), ('venue_monk', 'Venue Monk'), ('sloshout', 'Sloshout'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
