# Generated by Django 5.1.2 on 2024-11-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='bg_color',
            field=models.CharField(default='#FFFFFF', max_length=50),
        ),
    ]
